apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ampel.fullname" . }}
  labels:
    {{- include "ampel.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.ampel.config | toJson | nindent 4 }}
